name: Healthcheck Pipeline

on:
  push:
    branches:
      - main

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check server status
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-cicd-2024.fly.dev/version
          max-attempts: 3
          retry-delay: 5s

