name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          node-version: '20'
      - name: Install dependencias
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5001
      - name: deploy
        if: ${{ github.event_name == 'push' }}
        run: flyctl deploy --remote-only
        env: 
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Build fail
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with: 
          severity: error
          text: Build failed
          details: commit broke ${{ github.event.commits.url }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch 
      - name: New version success
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() }}
        with:
          severity: info
          text: A new version of pokedex deployed https://full-stack-open-pokedex-cicd-2024.fly.dev
          details: Healthcheck successful 
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
